### ISSUE TITLE
PEP8 Formatting Errors

### ISSUE THREAD

**Issue by arunk-s** [owtf/http-request-translator#24]
The code still has some parts that does not follow PEP8. Mixed spaces and tabs and too long lines of code are some of the primary issues.

**Comment by DePierre** [comment]
Fixed by 301a0e09b6596fe101ecbd9581d47329664ad492 thanks to @arunk-s awesome work :)

Some few PEP8 errors might be in the source code, but they will be fixed one day, when some random person will stumble upon it.
