### ISSUE TITLE
Do students need to work on this repo for GSoC?

### ISSUE THREAD

**Issue by dufferzafar** [owtf/http-request-translator#35]
The [OWASP GSoC Idea](https://www.owasp.org/index.php/GSOC2016_Ideas#OWASP_OWTF_-_HTTP_Request_Translator_Improvements) related to HTTP Request Translator does not link to this repo.

So, I was under the impression that we might have to create a new tool from scratch, and not update this code. Is that the case?

I think that the existing codebase isn't as clean as it can be and have some plans in mind regarding how we can structure our code so that it has an extensible architecture (something that is mentioned in the idea.)

I've recently added a similar feature (exporting requests as Python Code etc.) to [mitmproxy.](http://github.com/mitmproxy/mitmproxy/) Here are the relevant pulls: https://github.com/mitmproxy/mitmproxy/pull/884 & https://github.com/mitmproxy/mitmproxy/pull/916

If you're interested in a quick prototype of my design, I can get it done this weekend.

**Comment by DePierre** [comment]
@dufferzafar This would be the repo for HTTP Request Translator.

Have you checked the `dev` branch? If so, what would be your concerns regarding the code quality?

**Comment by dufferzafar** [comment]
I am sorry, but I was just looking at the `master` branch. :disappointed:

**Comment by DePierre** [comment]
@dufferzafar The master branch is outdated. We are going to merge the dev branch into it soon.

Have a look at the dev branch and feel free to comment the code, implement a prototype, etc. ;)
