### ISSUE TITLE
Upload the package to pypi.org

### ISSUE THREAD

**Issue by viyatb** [owtf/http-request-translator#61]
@DePierre, can you publish the tool on PyPI? Then we can easily integrate it in OWTF's web interface. (https://github.com/owtf/owtf/issues/829)

**Comment by DePierre** [comment]
@viyatb I will take care of creating the PyPi package in the next couple of days ;)

Keep in mind that this project is in alpha phase haha. But I'm very happy that it will be integrated in owtf because it will be a real use case and not just two random dudes running tests.

**Comment by viyatb** [comment]
@DePierre sure, no problem. Haha! The project has to mature sometime ;). We'll add features from Postman, and other relevant applications.

**Comment by DePierre** [comment]
@viyatb HTTP Request Translator is now available on PyPi: https://pypi.python.org/pypi/hrt/0.1.0

**Comment by viyatb** [comment]
@DePierre awesome, thanks!
